# site settings
title: Theoretical Chemistry  
subtitle: at Virginia Tech
email: nmayhall@vt.edu
description: 
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 900 West Campus Drive
city: Blacksburg 
state: VA
zip_code: 24061
country: United States of America
phone: 540-231-5391 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
